### ISSUE TITLE
Compile erro Hugo! Emulator

### ISSUE THREAD

**Issue by ryugold777** [mckayemu/hugo#1]
There is an error when trying to compile. The first error is the sdl path. Well I configure the path and appeared another error in code: 
error: macro names must be identifiers
error: static declaration of ‘BaseClock’ follows non-static declaration
hope will help you
thanks in advance!

**Comment by mckaygerhard** [comment]
use debian old old stable or gcc 4.X .. i do not make this for modern "want more requeriments" stupid  compilers.. that' why i forked the project in thi emulation group

**Comment by mckaygerhard** [comment]
as example.. seems The standard (C11 6.4.2 Identifiers) mandates that identifiers must not start with a digit, so its obvious you are using a stupid modern compiler on a recent linux that i really really hate! not cos tech cannot advance..  cos those advances raises requirements withour any need.. so the recent GNU compiler tools do not allow preprocessor identifiers that start with a number. renaming all the macros are a innecesary work cos the emulator are already working good very faster
